server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users
        - id: course-service
          uri: http://course-service:8082
          predicates:
            - Path=/courses/**, /modules/**
        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/enrollments/**
        - id: assessment-service
          uri: http://assessment-service:8084
          predicates:
            - Path=/assessments/**, /submissions/**
        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/notifications/** 

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

spring:
  sleuth:
    sampler:
      probability: 1.0

# Fallback endpoint example
# You need to implement a fallback controller for /fallback/users 