server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
        - id: course-service
          uri: http://course-service:8082
          predicates:
            - Path=/courses/**, /modules/**
        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/enrollments/**
        - id: assessment-service
          uri: http://assessment-service:8084
          predicates:
            - Path=/assessments/**, /submissions/**
        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/notifications/** 