server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/lms
    username: lms
    password: lms123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: course-service 